language: go

go:
  - 1.5

before_install:
  - export GOPATH=`pwd`/server
  - cd server/src/redbutton
install:
  - go get ./...
  - go build ./...

script:
  - go vet -x ./...
  - go test -v ./...
  - go test -covermode=count -coverprofile=profile.cov .