# build configuration for https://travis-ci.org

language: go

go:
  - 1.5
  - 1.5.3
  - 1.6rc1

install:
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -t ./...
  - go build ./...

script:
  - ./ci-scripts/check-formatting.sh
  - ./ci-scripts/check-linter-errors.sh
  - go vet -x ./...
  - go test -v ./...
