language: go

go:
  - 1.5
  - 1.6

install:
  - export GOPATH=$TRAVIS_BUILD_DIR/server
  - export PATH=$GOPATH/bin:$PATH
  - go get -u github.com/golang/lint/golint
  - cd $GOPATH/src/redbutton
  - go get -t ./...
  - go build ./...

script:
  - cd $GOPATH/src/redbutton
  - ../../../ci-scripts/check-formatting.sh
  - ../../../ci-scripts/check-linter-errors.sh
  - go vet -x ./...
  - go test -v ./...
