language: go

go:
  - 1.5

before_install:
  - cp $TRAVIS_BUILD_DIR/server/src/redbutton $GOPATH/src/ -rf
install:
  - go get ./...
  - go build ./...

script:
  - go vet -x ./...
  - go test -v ./...
  - go test -covermode=count -coverprofile=profile.cov .