language: go

go:
  - 1.5

before_install:
  - cd server/src/redbutton
install:
  - go get -d -v ./... && go build -v ./...

script:
  - go vet -x ./...
  - go test -v ./...
  - go test -covermode=count -coverprofile=profile.cov .