language: go

go:
  - 1.5

install:
  - export GOPATH=$TRAVIS_BUILD_DIR/server
  - export PATH=$GOPATH/bin:$PATH
  - go get -u github.com/golang/lint/golint
  - cd $GOPATH/src/redbutton
  - go get -t ./...
  - go build ./...

script:
  - cd $GOPATH/src/redbutton
  - ../../../ci-scripts/check-formatting.sh
  - go vet -x ./...
  - golint ./...
  - go test -v ./...
