- name: Prepare deployment
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: run build
      command: python build/build.py
      environment:
        GOROOT: /home/uiron/apps/go1.5