- name: terminate old instances
  hosts: tag_Name_red_button_old
  remote_user: ubuntu
  tasks:
    - name: gather current ec2 facts
      action: ec2_facts
    - name: terminating old instances
      local_action:
        module: ec2
        state: 'absent'
        region: 'eu-west-1'
        keypair: 'myapp'
        instance_ids: "{{ ansible_ec2_instance_id }}"


