- hosts: all
  gather_facts: False
  tasks:
    - debug: var=

- hosts: localhost
  connection: local
  gather_facts: False

- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'