
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Provision a set of new instances on AWS
      ec2:
         key_name: redbutton # ssh key
         region: eu-west-1
         group: default
         instance_type: t1.micro
         image: ami-de0fa5ad # ubuntu 14.04 LTS
         wait: true
         exact_count: 1
         count_tag:
            Name: red-button
         instance_tags:
            Name: red-button
      register: ec2

    - name: wait for ssh become available
      wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.instances


- hosts: ec2hosts
  name: upload files
  remote_user: ubuntu
  gather_facts: true

  tasks:
     - name: upload service binary
       copy: src=../bin/redbutton-server dest=~/redbutton-server mode="u=rwx,g-rwx,o-rwx"
     - name: start redbutton server
       command: ./redbutton-server
       environment:
         PORT: 80