- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create hosts on AWS
      ec2:
         key_name: redbutton # ssh key
         region: eu-west-1
         group: default
         instance_type: t2.micro
         image: ami-365cf745 # ubuntu 14.04 LTS
         wait: true
         count: 1
         count_tag:
            Name: red-button
         instance_tags:
            Name: red-button
      register: ec2

    - name: Wait for ssh become available
      wait_for: host={{item.public_ip}} delay=2 port=22 timeout=320 state=started search_regex=OpenSSH
      with_items: ec2.instances
