- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create hosts on AWS
      ec2:
         key_name: redbutton # ssh key
         region: eu-west-1
         group: default
         instance_type: t1.micro
         image: ami-de0fa5ad # ubuntu 14.04 LTS
         wait: true
         exact_count: 1
         count_tag:
            Name: red-button
         instance_tags:
            Name: red-button
      register: ec2

    - name: Wait for ssh become available
      wait_for: host={{item.public_ip}} port=22 timeout=320 state=started
      with_items: ec2.instances
