// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package ideal_server is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	HelloRequest
	HelloReply
*/
package ideal_server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*HelloRequest)(nil), "ideal_server.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "ideal_server.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for IdealServer service

type IdealServerClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type idealServerClient struct {
	cc *grpc.ClientConn
}

func NewIdealServerClient(cc *grpc.ClientConn) IdealServerClient {
	return &idealServerClient{cc}
}

func (c *idealServerClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/ideal_server.IdealServer/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IdealServer service

type IdealServerServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterIdealServerServer(s *grpc.Server, srv IdealServerServer) {
	s.RegisterService(&_IdealServer_serviceDesc, srv)
}

func _IdealServer_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(IdealServerServer).SayHello(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _IdealServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ideal_server.IdealServer",
	HandlerType: (*IdealServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _IdealServer_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc9, 0x4c, 0x49, 0x4d, 0xcc, 0x89,
	0x87, 0x88, 0x29, 0x29, 0x71, 0xf1, 0x78, 0xa4, 0xe6, 0xe4, 0xe4, 0x07, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x81, 0xd9, 0x4a, 0x6a, 0x5c, 0x5c, 0x50, 0x35, 0x05, 0x39, 0x95, 0x42, 0x12, 0x5c, 0xec,
	0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0x30, 0x45, 0x30, 0xae, 0x51, 0x20, 0x17, 0xb7, 0x27, 0xc8,
	0xec, 0x60, 0xb0, 0xd1, 0x42, 0x4e, 0x5c, 0x1c, 0xc1, 0x89, 0x95, 0x60, 0x9d, 0x42, 0x52, 0x7a,
	0xc8, 0xb6, 0xea, 0x21, 0x5b, 0x29, 0x25, 0x81, 0x55, 0x0e, 0x68, 0x95, 0x12, 0x43, 0x12, 0x1b,
	0xd8, 0xcd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xe0, 0x37, 0xfa, 0xc3, 0x00, 0x00,
	0x00,
}
