// -- go:generate swagger generate server --skip-support --api-package generated/operations -f ../api/swagger.spec.yml
//go:generate protoc server.proto --go_out=plugins=grpc:./

package ideal_server

import (
	"golang.org/x/net/context"
)

// all we care is about creating implementaiton for service
// as generated by the
type server struct {
}

func NewServer() IdealServerServer {
	return &server{}
}

// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *HelloRequest) (*HelloReply, error) {
	return &HelloReply{Message: "Hello " + in.Name}, nil
}
