// -- go:generate swagger generate server --skip-support --api-package generated/operations -f ../api/swagger.spec.yml


package ideal_server
import "github.com/viktorasm/redbutton/ideal_server/api"

// all we care is about creating implementaiton for service
// as generated by the
type server struct {

}

func (s*server) CreateNewRoom(api.NewRoom) api.RoomStatus {
	return api.RoomStatus{}
}

func NewServer() api.Service{
	return &server{}
}